### ISSUE TITLE
online_DHP

### ISSUE THREAD

**Issue by yunruoxu** [YuhangSong/DHP#46]
Hello，could you give the procedures to train and test online_DHP？Thank YOU!

**Comment by YuhangSong** [comment]
Sure, the code for online DHP is already implemented in the project, but
without a detailed readme. Sorry for the inconvenience. I am currently
working on the ddl of aaai conference. But I promise an update of online
dhp within 3 days after the paper submission ddl of aaai. And I will
mention you in this thread once I have done it so that you will receive
notification if you have your email linked to your git account.
yunruoxu <notifications@github.com>于2018年8月23日 周四下午2:33写道：

**Comment by yunruoxu** [comment]
OK. Thank you very much!

**Comment by YuhangSong** [comment]
I will be travelling for a few days but I am working on it. Might take a few more days, apologize for that.

**Comment by tjinjin95** [comment]
hello, I also hope you could give the procedures to train and test online_DHP？Thanks a lot. @YuhangSong @yunruoxu
